apiVersion: v1
kind: Secret
metadata:
  name: regcred
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJyZWdpc3RyeS5naXRsYWIucGFuZ29saW5sYWJzLmNuIjp7InVzZXJuYW1lIjoiY2ktYm90IiwicGFzc3dvcmQiOiJnaXRsYWJAY2kiLCJlbWFpbCI6ImNpQGdpdGxhYi5wYW5nb2xpbmxhYnMuY24iLCJhdXRoIjoiWTJrdFltOTBPbWRwZEd4aFlrQmphUT09In19fQ==
type: kubernetes.io/dockerconfigjson
